### PR TITLE
Add pull requests to the issues table

### PR DESCRIPTION
**Pull request by jdorweiler**
Adds an `is_pr` column and stores a `1` if the issue is a pull request.
@MariagraziaAlastra @jbarrett @russellholt

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Thanks! Could you please follow the instructions in #476, so it will be easy to upgrade our DBs?

**Comment by jdorweiler** [comment]
I added a sql file under `sql/1008/get_pr.sql`.

**Comment by jbarrett** [comment]
:+1: Cool. Could we rename the version directory to `1.008` just to be completely unambiguous?

Thanks.

**Comment by jdorweiler** [comment]
Good point.  I updated it.

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Looks good but apparently there's a conflict in ghIssues.pl. :cactus: 
Could you please resolve it so this can be merged?

**Comment by jdorweiler** [comment]
@MariagraziaAlastra thanks, all fixed now.

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Thank you! LGTM :+1:

**Pull request merged**
