### PR TITLE
More design fixes to the banner + notification.

### PR DESCRIPTION
**Pull request by jagtalon**
screen shot 2016-06-02 at 7 12 27 am
screen shot 2016-06-02 at 7 12 59 am
screen shot 2016-06-02 at 7 13 46 am
screen shot 2016-06-02 at 7 14 22 am
screen shot 2016-06-02 at 7 15 36 am
screen shot 2016-06-02 at 7 21 26 am

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Is this ready to review?

**Comment by jagtalon** [comment]
@MariagraziaAlastra yes I think the code is ready to be reviewed, but I'd like to give it one more design pass before merging.

**Comment by MariagraziaAlastra** [comment]
@jagtalon Sure

**Comment by MariagraziaAlastra** [comment]
LGTM 👍

**Pull request merged**
