### PR TITLE
ghIssues.pl - only get the thread ID for the forum_link column

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
Fixes the wrong href in the forum thread anchor tag, inside the single IA Pages

### CODE REVIEW

**Comment by jdorweiler** [comment]
I updated the regex in ghIssues to only get duck.co idea links and removed some other bad forum links in the forum_links script.  Here's the results I got 
Before:
selection_006

After:
selection_007

**Comment by jdorweiler** [comment]
hmm sorry for the potato images.  Not sure what's going on there :frowning:

**Comment by MariagraziaAlastra** [comment]
@jdorweiler When running the script inside sql/1.078/ I get various instances of these two errors:
<pre>https://duck.co/ideas/idea/5235/is-there-anything-we-could-do-using-this-api-dec at sql/1.078/forum_link.pl line 15.
Use of uninitialized value in concatenation (.) or string at /usr/local/ddh/community-platform/sql/1.078/../../lib/DDGC/DB/Base/Result.pm line 278.
Use of uninitialized value in concatenation (.) or string at /usr/local/ddh/community-platform/sql/1.078/../../lib/DDGC/DB/Base/Result.pm line 278.
https://duck.co/ideas/idea/802/pluralize-english-words at sql/1.078/forum_link.pl line 15.
</pre>

<pre>Use of uninitialized value $value in join or string at /usr/local/ddh/community-platform/sql/1.078/../../lib/DDGC/DB/Result/InstantAnswer.pm line 461.
https://duck.co/ia/view/cpp_strings_cheat_sheet at sql/1.078/forum_link.pl line 15.
</pre>

It doesn't block the execution, but it's still weird

**Comment by jdorweiler** [comment]
@MariagraziaAlastra not sure but looking through the history of that line `lib/DDGC/DB/Base/Result.pm line 278` it seems to be related to notifications.

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Or maybe undefined forum_link values

**Comment by MariagraziaAlastra** [comment]
The issue is not directly related to the script, which works perfectly; instead, it's something to do with notifications failing.

Made sure it didn't break anything, so now I'll merge.
Thanks @jdorweiler! :cactus:

**Comment by jdorweiler** [comment]
great thanks for testing @MariagraziaAlastra

**Pull request merged**
