### PR TITLE
Header and footer redesign 👌💃

### PR DESCRIPTION
**Pull request by jagtalon**
- Remove linear-gradients. Interesting fact about -ms-linear-gradient: http://codepen.io/thebabydino/full/pjxVWp/. It never existed! 👻

For: @MariagraziaAlastra

### CODE REVIEW

**Comment by jagtalon** [comment]
screen shot 2016-01-14 at 5 06 55 pm

**Comment by jagtalon** [comment]
screen shot 2016-01-19 at 4 09 13 pm
screen shot 2016-01-19 at 4 09 19 pm

**Comment by jagtalon** [comment]
## Various pages:

screen shot 2016-01-26 at 11 42 17 am
screen shot 2016-01-26 at 11 53 24 am
screen shot 2016-01-26 at 11 53 30 am
screen shot 2016-01-26 at 11 53 34 am
screen shot 2016-01-26 at 11 53 39 am
screen shot 2016-01-26 at 11 53 42 am
screen shot 2016-01-26 at 11 54 11 am

## IE 10

screen shot 2016-01-26 at 11 31 51 am
screen shot 2016-01-26 at 11 31 57 am
screen shot 2016-01-26 at 11 33 05 am

## IE 11

screen shot 2016-01-26 at 11 33 54 am
screen shot 2016-01-26 at 11 34 01 am
screen shot 2016-01-26 at 11 34 39 am

## Edge

screen shot 2016-01-26 at 11 35 42 am
screen shot 2016-01-26 at 11 35 48 am
screen shot 2016-01-26 at 11 36 27 am

## FF

screen shot 2016-01-26 at 11 37 46 am
screen shot 2016-01-26 at 11 37 53 am

## iOS

screen shot 2016-01-26 at 11 39 16 am
screen shot 2016-01-26 at 11 39 22 am
screen shot 2016-01-26 at 11 40 02 am

## Android

screen shot 2016-01-26 at 11 40 57 am
screen shot 2016-01-26 at 11 41 55 am
screen shot 2016-01-26 at 11 41 59 am

**Comment by russellholt** [comment]
Looks great, @jagtalon

**Comment by MariagraziaAlastra** [comment]
@jagtalon Testing now. Looks awesome! :cactus: 
Just one thing, so far: what about using cursor: pointer on the username link?

**Comment by jagtalon** [comment]
@MariagraziaAlastra good point. added

**Comment by MariagraziaAlastra** [comment]
Awesome, thanks @jagtalon!

**Pull request merged**
