### PR TITLE
InstantAnswer.pm - fix create_ia (called from the new IA wizard page)

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
##### Description :
Creating a new IA (both from scratch and from a PR link) is broken on the live site.
Problem was a typo (a second "my" which made it look like the variable was different from the one defined previously for the maintainer).
While I was at it I also fixed a bug with contributor names when the author type is "github" (previously used the duck.co username, now it uses the github login)

##### Reviewer notes :
If you want to test this manually, log in as a user with a github account connected and try creating an IA from ia/new_ia.
Expected: the page is created and you're set as maintainer and added as contributor, both using your github account.

##### References issues / PRs:
Nope

##### Who should be informed of this change?
@tagawa, who spotted the bug!

##### Does this change have significant privacy, security, performance or deployment implications?
I need to deploy this as hotfix now and then it'll be included in the next regular deployment as well.

##### Checklist :
- [x] Back end tests (perl, scripts)
- [ ] Front end tests (js, integration) 
- Browser verification
    - [ ] IE
    - [ ] Chrome
    - [x] Firefox
    - [ ] Safari
    - [ ] Opera 
- Mobile verification
    - [ ] iOS
    - [ ] Android

### CODE REVIEW

**Comment by tagawa** [comment]
Grazie @MariagraziaAlastra!

**Comment by MariagraziaAlastra** [comment]
@jbarrett Added more tests

**Comment by jbarrett** [comment]
:+1: Thanks @MariagraziaAlastra! Test looking good. Let me know when you're happy to merge.

**Comment by MariagraziaAlastra** [comment]
@jbarrett if you're happy, I'm happy to merge now too!

**Pull request merged**
