### PR TITLE
additions to /ia/repo

### PR DESCRIPTION
**Pull request by russellholt**
add some necessary data to this endpoint to be used in the metadata publishing. it's structured slightly differently than /ia/json in that this one is a hash of ia data by id.

`/ia/repo/goodies/json` entries look like

```
"loan": {
    "perl_module": "DDG::Goodie::Loan",
    "status": "live",
    "name": "Loan",
    "example_query": "loan $500000 at 4.5% with 20% down",
    "description": "Calculate monthly payment and total interest for conventional mortgage",
    "repo": "goodies",
    "tab": null,
    "id": "loan"
},
```

and an entry from `/ia/repo/fathead/json` looks like

```
"muppet_wiki": {
    "perl_module": "DDG::Fathead::MuppetWiki",
    "status": null,
    "name": "MuppetWiki",
    "example_query": "elmo muppets",
    "description": "Muppets reference",
    "src_id": 10,
    "src_options":  {
        "skip_abstract_paren": "",
        "skip_end": "",
        "skip_abstract": "",
        "skip_qr": "Muppet Wiki",
        "skip_icon": "",
        "skip_image_name": "",
        "is_mediawiki": "1"
    },
    "repo": "fathead",
    "tab": null,
    "id": "muppet_wiki"
}
```

### CODE REVIEW

**Comment by russellholt** [comment]
@jdorweiler don't know if you want to add anything?

**Comment by MariagraziaAlastra** [comment]
@russellholt Looks good! If you don't have anything else to add feel free to merge :)

**Comment by russellholt** [comment]
@MariagraziaAlastra I'll wait for jason's ok

**Comment by jdorweiler** [comment]
@russellholt @MariagraziaAlastra looks good to me.  I can't think of any other data I would need.

**Pull request merged**
