### PR TITLE
update dev database with live json data

### PR DESCRIPTION
**Pull request by jdorweiler**
Truncates all tables and rebuilds with data from `/ia/view/<IA>/json`
@MariagraziaAlastra @russellholt

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Awesome, thanks! Just got back home, will look at the code more in depth and test it tomorrow! :rocket:

**Comment by MariagraziaAlastra** [comment]
@jdorweiler What about adding some optional arguments, so we'd had the ability to specify just a repo or just one IA Page? The update process seems a bit long and we often know exactly what IA Page has the faulty data. 
What do you think? It can be done on a separate PR anyway :)

**Comment by jdorweiler** [comment]
@MariagraziaAlastra Yeah good idea. I'll add those options.

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Deprecated IAs aren't imported (the pages don't exist at all) for some reason. Also, the dev pipeline on my instance and the duck.co one have different IAs.
Dev pipeline on my instance:
screenshot-maria duckduckgo com 5000 2015-05-15 12-00-20
On duck.co:
screenshot-duck co 2015-05-15 12-00-47

**Comment by jdorweiler** [comment]
@MariagraziaAlastra The IAs that are not in development status don't show up in the repo endpoint so I can't get those.

**Comment by jdorweiler** [comment]
@MariagraziaAlastra added --ia and --repo options.

**Comment by MariagraziaAlastra** [comment]
Great, thanks! LGTM :+1:

**Pull request merged**
