### PR TITLE
Nix API usage for blog frontend.

### PR DESCRIPTION
**Pull request by jbarrett**
Cc: @jkv 

My test plan:

- Paging
  - 20 posts per page
  - Page count correct
  - Posts are in descending chronological order
  - All pages start with the post chronologically before the last one on the previous page
  - Pages can be filtered by topic
    - Page count is correct for topic filtered posts
    - Only posts with that topic are shown
- Posts
  - Legacy links work, /blog/$uri form
  - Correct number of comments shown
  - Correct poster, has admin badge
  - Teaser shown on front page, full content on blog post page
- Posting (nothing has changed here)
  - Edit links work for admins
  - Delete links work for admins
- Commenting
  - Can comment on posts
  - Threading is preserved

This is sub-optimal, but here's a quick way to create posts if you need to...

```sql
INSERT INTO user_blog
    values (
        DEFAULT, 1,
        'title',
        'uri',
        'teaser',
        'content',
        '["topic1","topic2"]',
        1, 'markdown', 1, 0, DEFAULT, NOW(), NOW()
    );
```

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jbarrett I get 404 for the blog. I just ran the server as usual, do I need to do anything else?

**Comment by jbarrett** [comment]
@MariagraziaAlastra You probably have no posts - I think I need to revert to the posts not found message rather than a straight up 404.

**Comment by MariagraziaAlastra** [comment]
@jbarrett Oh ok, thanks :smile:

**Comment by jbarrett** [comment]
Marking this WIP until I fix the 404 on the posts index where there are no posts

**Comment by MariagraziaAlastra** [comment]
@jbarrett Looks good, besides the 404 thing :+1:

**Comment by jbarrett** [comment]
I don't know where I got the idea that I had a custom 404 for this.

Anyway, the page with just '404' on it is fine - that gets intercepted by nginx and a styled 404 page is displayed:

https://duck.co/blog/post/9999/foo

[This file](https://github.com/duckduckgo/community-platform/blob/98a7187/root/static/pages/404.html) needs to be updated for new styles, but that's out of scope for this PR.

Thanks @MariagraziaAlastra! Merge when ready.

**Comment by MariagraziaAlastra** [comment]
@jbarrett Oh, I just got "404", not the styled version. Literally a blank page with the "404" text. Well anyway, we have posts on our blog so that's not really an issue :smile: 

Thanks, merging! :+1:

**Comment by jbarrett** [comment]
There's at least one more issue to work out - since the URL scheme changed, there's support for legacy links of the form /blog/$uri - this appears not to be working

**Comment by MariagraziaAlastra** [comment]
Ok, not merging then!

**Comment by jbarrett** [comment]
Phew! ;)

**Comment by jbarrett** [comment]
OK, should be sorted now - You should be able to get a blog post from just the URL, so if you have a post '/blog/post/10/foo', going to '/blog/foo' will take you to '/blog/post/10/foo' (or an earlier post matching this uri).

**Comment by MariagraziaAlastra** [comment]
@jbarrett Yeah, works as expected! Happy to merge?

**Comment by jbarrett** [comment]
:+1: Thanks!

**Comment by MariagraziaAlastra** [comment]
:cactus:

**Comment by jbarrett** [comment]
:deciduous_tree:

**Pull request merged**
