### PR TITLE
Add the blue header

### PR DESCRIPTION
**Pull request by jagtalon**
screen shot 2015-10-22 at 1 35 26 pm

Here's what it currently looks like:
screen shot 2015-10-22 at 1 36 14 pm

### CODE REVIEW

**Comment by jagtalon** [comment]
This should be good. I need to make another PR though to make the sidebar go under the blue bar screen shot 2015-10-22 at 2 05 49 pm

**Comment by jagtalon** [comment]
Setting back to WIP--some elements are need to only be shown when the user is authenticated.

**Comment by jagtalon** [comment]
@MariagraziaAlastra should be ready for another review!

**Comment by jagtalon** [comment]
screen shot 2015-10-26 at 10 47 42 am

**Comment by MariagraziaAlastra** [comment]
@jagtalon Could you put the home / dev pipeline / issues / deprecated stuff under the title, like in the mockup, as links?

**Comment by jagtalon** [comment]
@MariagraziaAlastra So we're removing the Created Today, Created This Week, etc?

**Comment by MariagraziaAlastra** [comment]
@jagtalon Just comment that stuff out

**Comment by jagtalon** [comment]
@MariagraziaAlastra gotcha thanks

**Comment by jagtalon** [comment]
screen shot 2015-10-26 at 11 21 28 am

**Comment by jagtalon** [comment]
@MariagraziaAlastra what do you think?

**Comment by MariagraziaAlastra** [comment]
@jagtalon nice, thanks, testing it!

**Comment by MariagraziaAlastra** [comment]
Looks good, thanks! :+1:

**Comment by jagtalon** [comment]
Nice thanks

**Pull request merged**
