### PR TITLE
Improve speed of compiling SCSS files.

### PR DESCRIPTION
**Pull request by jagtalon**
Continuation of https://github.com/duckduckgo/community-platform/pull/1091

### CODE REVIEW

**Comment by jagtalon** [comment]
@MariagraziaAlastra the SCSS changes are here because we moved to 1.) libsass which meant no longer using compass, but we're still using compass mixins and 2.) some mixins are completely unnecessary such as @include border-radius http://caniuse.com/#search=border-radius

**Comment by jagtalon** [comment]
@MariagraziaAlastra this is ready (thanks to @jbarrett for the help on the live reloading)

**Comment by jagtalon** [comment]
@MariagraziaAlastra you can test live reload by running `grunt watch` and changing one of the files like in here https://www.youtube.com/watch?v=EkVMkRQHcP4

**Comment by MariagraziaAlastra** [comment]
Thanks @jagtalon, going to test it soon!

**Comment by MariagraziaAlastra** [comment]
@jagtalon I get an error when running grunt watch, or even just grunt:
<pre>Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'load-grunt-tasks'
Warning: Task "default" not found. Use --force to continue.
</pre>

**Comment by MariagraziaAlastra** [comment]
@jagtalon Cool, it works fine on my instance, although I had to remove npm_modules and bower_components before running npm install, as you suggested.
@jbarrett Final sign off on this?

**Comment by jagtalon** [comment]
@jbarrett final thoughts? :)

**Comment by jbarrett** [comment]
@MariagraziaAlastra If you're happy with it, :+1:

**Comment by jagtalon** [comment]
@MariagraziaAlastra @jbarrett thanks!

**Pull request merged**
