### PR TITLE
Blog: Added link to developer newsletter

### PR DESCRIPTION
**Pull request by tagawa**
##### Description :
Added a link to the blog sidebar for the weekly developer newsletter

##### References issues / PRs:

#

##### Who should be informed of this change?
@jbarrett @zekiel 

##### Does this change have significant privacy, security, performance or deployment implications?
No, just a bit of HTML

##### Checklist :
- [ ] Back end tests (perl, scripts)
- [ ] Front end tests (js, integration)
- Browser verification
    - [ ] IE
    - [ ] Chrome
    - [X] Firefox
    - [ ] Safari
    - [ ] Opera 
- Mobile verification
    - [ ] iOS
    - [ ] Android

### CODE REVIEW

**Comment by jbarrett** [comment]
@tagawa Let me know when this is ready to go.

**Comment by tagawa** [comment]
@zekiel What do you think about adding this?

sidebar-newsletter-link

**Comment by zekiel** [comment]
@tagawa  seems fine to me. Not sure what the impact is going to be or if we're going to hop blog services in the future.

**Comment by tagawa** [comment]
Thanks @zekiel. Just a small change but for the effort, worth adding I think.

@jbarrett Ready to go please!

**Comment by jbarrett** [comment]
:+1: Thanks @tagawa, @zekiel!

**Comment by tagawa** [comment]
And thanks for the merge @jbarrett

**Pull request merged**
