### PR TITLE
Login / Reg form changes

### PR DESCRIPTION
**Pull request by jbarrett**
- Stop using randomised field names
- Stop using captcha
- Start using CSRF token

Cc: @MariagraziaAlastra @jdorweiler 

Other potential changes coming in separately - I've made the mistake of trying to conflate too many changes in one PR before... One assumption winds up being invalid, all the other work has to go.

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jbarrett After I sign up, when I try to login it says "Login failed. Your username or password is incorrect."

**Comment by jbarrett** [comment]
Bet it works in Private Browsing mode.

**Comment by MariagraziaAlastra** [comment]
@jbarrett Oh yeah it does! I forgot about this private browsing mode thing, although I remember encountering it previously too.
Anyway, looks good to me! :+1:

**Comment by jbarrett** [comment]
Thanks @MariagraziaAlastra - problem is the browser auto-filling hidden fields if you have it store passwords and such.

**Pull request merged**
