### PR TITLE
Markdown blog posts

### PR DESCRIPTION
**Pull request by jbarrett**
Was : #767

### CODE REVIEW

**Comment by jbarrett** [comment]
Going to learn to use Git some day ;)

https://view.dukgo.com/ - ping me if you need an admin account.

**Comment by zekiel** [comment]
nice -- did some testing copying the docs pages over to a blog post. Works well! Just changing code highlighting from github flavor ``` to regular markdown (4 space indent at new line) is the main difference

**Comment by jbarrett** [comment]
Do we often have code snippets in blog posts?

While markdown has been requested for comments, I don't have immediate plans to enable them there.

**Comment by zekiel** [comment]
I'm almost certain that we will -- if we haven't in the past. Slightly confused tho--it's already supported via regular markdown syntax (4 space indentation on each line). 

I wasn't talking about comments -- just regular blog posts.

**Comment by jbarrett** [comment]
Ah, would you look at that, the highlighter kicks in and everything. I'm happy enough with that for now.

**Pull request merged**
