### PR TITLE
Fixing browse tokens view

### PR DESCRIPTION
**Pull request by jbarrett**

### CODE REVIEW

**Comment by jbarrett** [comment]
TBD: Untranslated view.

**Comment by preemeijer** [comment]
Thanks John for working on this! I will follow it by adding myself as a participant... but unfortunately not as a programmer... Greetings, Paul

**Comment by jbarrett** [comment]
Thanks @preemeijer, looking at a Monday release for this with luck.

**Comment by preemeijer** [comment]
Thank you! ^_^

**Pull request merged**
