### PR TITLE
ghissues regex bug and added transactions 

### PR DESCRIPTION
**Pull request by jdorweiler**
The delete/update is done in a transaction so it will roll back on any errors.  
@MariagraziaAlastra @russellholt @jbarrett

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Uhm, I tried running this on my instance and the new issues in which I added the IA Page link aren't showing up... plus I get this message:

```
HTTP::Server::PSGI: Accepting connections at http://0:5000/
DBIx::Class::Storage::DBI::select_single(): Query returned more than one row.  S                                                                                        QL that returns multiple rows is DEPRECATED for ->find and ->single at /home/ubu                                                                                        ntu/community-platform/script/../lib/DDGC/Web/Controller/InstantAnswer.pm line 1                                                                                        72
```

**Comment by MariagraziaAlastra** [comment]
Uhm, so it looks like the problem might be [line 172 of InstantAnswer.pm](https://github.com/duckduckgo/community-platform/blob/dev/lib/DDGC/Web/Controller/InstantAnswer.pm#L172), because "find" gets just one row, but we want to retrieve multiple ones.

**Comment by MariagraziaAlastra** [comment]
Fixed that error in #485, but I still don't see the latest issues I added. For example [this one for AlternativeTo](https://github.com/duckduckgo/zeroclickinfo-spice/issues/1305) isn't showing up.

**Comment by jdorweiler** [comment]
@MariagraziaAlastra Thanks for checking it out.  Looks like the api only gives 30 issues at a time so I'll have to update it to get multiple pages.

**Comment by jdorweiler** [comment]
okay,  now with fewer bugs!

**Comment by MariagraziaAlastra** [comment]
@jdorweiler haha, thank you! Works like a charm now :+1:

**Pull request merged**
