### PR TITLE
IA Pages - Add endpoints for the Dev Pipeline

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
WIP! I'd like to get at least some basic layout done before merging this.

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
screen shot 2015-02-19 at 17 22 08

**Comment by jagtalon** [comment]
@MariagraziaAlastra looks like you're missing IADevPipeline.js?

**Comment by MariagraziaAlastra** [comment]
Oh. Sorry, forgot to add it... :neutral_face:

**Comment by MariagraziaAlastra** [comment]
@jagtalon Added it

**Comment by jagtalon** [comment]
@MariagraziaAlastra looking good! :+1:

**Pull request merged**
