### PR TITLE
Notification system

### PR DESCRIPTION
**Pull request by jbarrett**

### CODE REVIEW

**Comment by jbarrett** [comment]
Example : User testone has had someone @ mention their name in a forum post. Let's retrieve the notification's details:

```
$ use lib 'lib'; use DDGC; my $d = DDGC->new; use DDP;
$DDGC1 = DDGC=HASH(0x245f880);

$ my $user = $d->find_user('testone')
SELECT "me"."id", "me"."username", "me"."public", "me"."email_notification_content", "me"."admin", "me"."ghosted", "me"."ignore", "me"."email", "me"."userpage", "me"."data", "me"."notes", "me"."profile_media_id", "me"."created", "me"."updated", "me"."roles", "me"."flags"
  FROM "users" "me"
WHERE LOWER( me.username ) LIKE 'testone'
DDGC::DB::Result::User #1

$ my $notifications = $user->unseen_notifications
SELECT COUNT( * )
  FROM "user_subscriptions" "me"
  JOIN "event" "events"
    ON ( "me"."target_object_id" = '0' OR "me"."target_object_id" = ANY( events.object_ids ) ) AND "events"."created" >= "me"."created" AND "events"."subscription_id" = "me"."subscription_id"
WHERE "me"."users_id" = '1'

$ $notifications->first->event_objects->first->content;
SELECT "events"."id", "events"."users_id", "events"."subscription_id", "events"."object", "events"."object_ids", "events"."target_object_id", "events"."created"
  FROM "user_subscriptions" "me"
  JOIN "event" "events"
    ON ( "me"."target_object_id" = '0' OR "me"."target_object_id" = ANY( events.object_ids ) ) AND "events"."created" >= "me"."created" AND "events"."subscription_id" = "me"."subscription_id"
WHERE "me"."users_id" = '1'
SELECT "me"."id", "me"."users_id", "me"."content", "me"."context", "me"."context_id", "me"."deleted", "me"."readonly", "me"."is_html", "me"."data", "me"."created", "me"."updated", "me"."ghosted", "me"."checked", "me"."parent_id"
  FROM "comment" "me"
WHERE "id" IN ( '1236' )

Hello @testone
```

**Comment by zekiel** [comment]
sync up on this when you're avail?

**Comment by jbarrett** [comment]
Sure, I just want to get a few more things wired up and pushed so you can *see* something :)

**Comment by jbarrett** [comment]
@zekiel I am currently implementing discussion related notifications. I am kind of following the existing model, but we can do anything we like here. Some discussion points:

- We thread conversations. Do we want to flatten them? (Not sure where this was discussed before)
  - Threading means we should track actual responses in events - if it's not in the branch of discussion you created then don't notify
  - No threading means subscribing to all further discussion in the thread (the way 'follow' works now).
  - We can also thread and have naive follow.

Some events with "instant" notification (i.e. the event refers to one object instance like a thread) are implemented - new thread in subbed forum and @-mention for now. New comments should be aggregate notifications, gathered every half-hour or hour.

**Comment by jbarrett** [comment]
For moderation notifications, should the number accumulate or be reset when notified?

**Comment by zekiel** [comment]
@jbarrett  

My expectation (tho maybe not representative of the majority) is that I will receive notifications: 
   -> for direct replies/actions on my submitted content (posts, comments, whatever) 
   -> for top-level events in things I voluntarily subscribe to (e.g. I subscribe to an IA idea, so I only get the main comments, not sub-comments  and I get other high-level updates on that IA idea like status changes, etc.) 

does that make sense? 

mod:   represent whatever is in the queue when the notification is generated (so accum)

**Comment by jbarrett** [comment]
Direct replies = first child comment or all descendent comments? Both possible, former easier :)

**Comment by zekiel** [comment]
direct replies == child comments

**Comment by jbarrett** [comment]
Something else in the works.

**Pull request closed without merging**
