### PR TITLE
Ideas: Push the votes back to the right.

### PR DESCRIPTION
**Pull request by jagtalon**
Old:

screen shot 2015-07-22 at 2 12 33 pm

New:

screen shot 2015-07-22 at 2 12 41 pm

### CODE REVIEW

**Comment by jagtalon** [comment]
screen shot 2015-07-22 at 2 14 01 pm

screen shot 2015-07-22 at 2 14 07 pm

**Comment by jbarrett** [comment]
I think I'd rather figure out where these rules went.

I need some help digging into history since I don't understand css, scss or the build system.

I've attempted to bisect from 0dc490e (which is good, release 1.058) - attempting to rebuild the css for each commit is not a valid approach since some revisions do not build, so I just went through with incomplete CSS looking at "vote on left" vs "vote on right", ignoring other stuff. That came up with 2ed0659 - would appreciate any help you can provide reviewing this @jagtalon @MariagraziaAlastra 

Something to do with those removed media rules? They appear to be in use on forum and idea pages.

**Comment by MariagraziaAlastra** [comment]
@jbarrett Yeah it's definitely those rules, especially [this one](https://github.com/duckduckgo/community-platform/commit/2ed06595d527d81e8c9861c9debadc9287398702#diff-64a612c667686eae6bf77ba7505abd89L393).
I guess then it's just a matter of putting those rules back in place.

**Comment by jbarrett** [comment]
I'd like to understand how they went missing too... but yeah, just put them back in place to see...

Yup

**Comment by jbarrett** [comment]
linking #837

**Comment by MariagraziaAlastra** [comment]
Right, @jagtalon did you remove them on purpose or was that by accident?
I should have tested that PR more extensively, too.

**Comment by jbarrett** [comment]
I wonder if we can hijack @andrey-p's work to automate this kind of evaluation? I think we'd need actial CI first, right?

**Comment by jagtalon** [comment]
@MariagraziaAlastra @jbarrett https://github.com/duckduckgo/community-platform/pull/838

**Pull request closed without merging**
