### PR TITLE
Programming Mission Onboarding Updates

### PR DESCRIPTION
**Pull request by alohaas**
##### Description :
In an effort to reduce distractions and consolidate the onboarding experience for new users, I've made changes to the header, footer, and blog navigation including:

- Remove "Help" from the Duck.co navigation
- Point all links to duck.co homepage to duckduckhack.com 
- Update the "Instant Answers" link to point to "Live IAs" rather than the "Overview"
- Add a link to the forum to the footer
- Update "Swag" links to hit the shopify store

cc: @zekiel @russellholt @tagawa @moollaza

### CODE REVIEW

**Comment by zekiel** [comment]
@alohaas  what's blocking this?

**Comment by alohaas** [comment]
@zekiel I need to get some code review.
@russellholt, @MariagraziaAlastra or @jbarrett are you available?

**Comment by alohaas** [comment]
Thanks for volunteering @MariagraziaAlastra 💪

**Comment by MariagraziaAlastra** [comment]
@alohaas Hey, no problem! :smile:
The link on the duck.co logo isn't changed in the blog header, though (we have different templates for the blog). 
[This](https://github.com/duckduckgo/community-platform/blob/753172e2a5cdf9722aca77f3e66cff03de1e8631/views/includes/header/index.tx) should be the header template for the blog!

**Comment by alohaas** [comment]
@MariagraziaAlastra I've made the changes to the other blog header template. Thanks!

**Comment by MariagraziaAlastra** [comment]
Thanks @alohaas, this LGTM! :+1:

**Pull request merged**
