### PR TITLE
Update favicon

### PR DESCRIPTION
**Pull request by bsstoner**
Not sure how to test this. I'm also not sure what the 3 different files are used for, but I'm assuming @chrismorast wants them all updated to the new one:

png

@jbarrett 
cc @chrismorast @sdougbrown

### CODE REVIEW

**Comment by jbarrett** [comment]
@chrismorast @bsstoner Are we still holding off on this?

**Comment by chrismorast** [comment]
Well, the idea was that we would fix the community platform favicon to see if the format looks okay. Doesn't look like that one was ever updated.

@bsstoner , there should only be a single file for the favicon with 5 sizes embedded.

**Comment by bsstoner** [comment]
Can you point me to the red asset?

**Comment by bsstoner** [comment]
The same one from duckduckgo.com?

**Comment by chrismorast** [comment]
No, the one posted here: https://app.asana.com/0/139850194016/47808821309970

**Comment by bsstoner** [comment]
Updated!

**Comment by chrismorast** [comment]
:+1:

**Pull request merged**
