### PR TITLE
'Active' flag on domains to remove expired domains from translation interface.

### PR DESCRIPTION
**Pull request by jbarrett**
- Admin interface for domains has an 'Active' option - set to 'No' to hide this domain in the translation interface.

@zekiel @yegg Thanks.

### CODE REVIEW

**Comment by jbarrett** [comment]
https://view.dukgo.com/ - ping me if you need an admin account.

**Comment by darkehorselll** [comment]
John Im still trying to sort out My Aerospace ties ...I can make you a account at google admin ...I cant pay you now but possibly in the future ....I need a webmaster elite bad ...

**Comment by zekiel** [comment]
@jbarrett looks like it's still accessible through the wizard and direct URL. All new registrations will prompt for the wizard .

**Comment by jbarrett** [comment]
Thanks for testing @zekiel. I've made some changes which are now on view.

**Comment by zekiel** [comment]
:+1:   

*note: still shows the Wizard prompt but it says "you finished the wizard" when clicked

screen shot 2015-02-26 at 5 04 31 pm

**Comment by jbarrett** [comment]
Thanks @zekiel. I inactivated the two domains on duck.co - seems OK to me.

**Comment by zekiel** [comment]
lgtm

**Pull request merged**
