### PR TITLE
Dev Pages - multiple selection for topics

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
@russellholt @jagtalon 
I think three topics should be more than enough for an IA:
schermata 2015-02-24 alle 21 31 39

Removing a topic doesn't actually remove the select element, it just empties the first option value and sets that one as selected, and then saves the new list of topics:
schermata 2015-02-24 alle 21 31 51

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
If we decide we want to limit the number of other queries, too, I'll probably use the same approach on the editable page, since it seems more straightforward and less convoluted than removing the actual element and then having to click on the "+" button to get a new one.

**Comment by russellholt** [comment]
@MariagraziaAlastra I agree about limiting the topics. makes it easier.

**Comment by russellholt** [comment]
about other queries - what about just a text area, one query per line?

**Comment by MariagraziaAlastra** [comment]
@russellholt That would mean more human error. You would have to explain "please each query on a newline" to everyone... I can already imagine the results

**Pull request merged**
