### PR TITLE
Pipeline (CSS + HTML): Style the search box.

### PR DESCRIPTION
**Pull request by jagtalon**
Style it to look like https://projects.invisionapp.com/share/ER482O582#/screens. For @MariagraziaAlastra

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jagtalon Looks good, but maybe the text should be darker (eg $slate) when typing the search string?
Also if you want you can put it above the milestones columns.

**Comment by jagtalon** [comment]
@MariagraziaAlastra updated.

**Comment by MariagraziaAlastra** [comment]
@jagtalon When multiselecting the actions get pushed on a new line:
screenshot-maria duckduckgo com 5001 2015-10-05 18-59-57

**Comment by jagtalon** [comment]
@MariagraziaAlastra gotcha. fixed

**Comment by jagtalon** [comment]
Gonna get this merged with master instead. Closing.

**Pull request closed without merging**
