### PR TITLE
dont update any existing data from the db

### PR DESCRIPTION
**Pull request by jdorweiler**
When auto creating IA pages the ID was being changed whenever the name changed.  This caused the duplicated IA pages.  It also caused the problem that @zachthompson saw where he updated the name and it reverted back the next time ghIssues ran. 

To fix this I'm getting the IA page from the DB and only updating `undef` fields.  Any fields from the DB that are already set will remain unchanged. 
@MariagraziaAlastra @russellholt

### CODE REVIEW

**Comment by russellholt** [comment]
:+1:

**Comment by MariagraziaAlastra** [comment]
@jdorweiler I got this error message while executing the script: <pre>
Use of uninitialized value $ENV{"DDGC_PROSODY_USERHOST"} in string ne at /home/ubuntu/community-platform/script/../lib/DDGC.pm line 31.
</pre>

**Comment by MariagraziaAlastra** [comment]
Anyway it works - just want to know what that message is about and see if we can do something before merging. Thanks!

**Comment by MariagraziaAlastra** [comment]
Merging, a fix for that error is already in dev-community (thanks @jbarrett).
Great job @jdorweiler! :+1:

**Pull request merged**
