### PR TITLE
Fixing user deletion

### PR DESCRIPTION
**Pull request by jbarrett**
While the robustness of our Prosody "integration" needs to be evaluated (#437), we can provide some fixes for the brokenness right now. This should address:

#363 - Deleted users not completely deleted 

Prosody usernames are made lowercase prior to storing them, so we should select on a lowercase username.

#325 - Don't bump forum posts when comments set to deleted user

Explicitly setting the updated date to equal created prevents this.

### CODE REVIEW

**Comment by jbarrett** [comment]
@zekiel This currently just sets the thread's user to 'deleted'.

Setting the thread title to "This user has been deleted" is not useful. I guess we could add it to the hidden pile.

**Comment by jbarrett** [comment]
http://view.dukgo.com/

**Comment by zekiel** [comment]
login is failing appropriately after deletion. 

@jbarrett  doesn't appear to work for IA ideas. GenRamblings will set to deleted user but Ideas remain w/ author and content.

**Comment by jbarrett** [comment]
@russellholt @MariagraziaAlastra @jdorweiler What should happen to IA attribution etc. when a user deletes their account?

@zekiel Each contribution type needs explicit and specific handling which has to be decided, so every new thing that gets added, someone has to know to handle it in the delete code... :)

**Comment by MariagraziaAlastra** [comment]
@jbarrett This is open for discussion, afaik we didn't think about this possibility.
Imho if the user created any IAs he should be asked whether he would like to keep its name without the link to the profile page, or use the github account for the link, or just have every reference to him removed.

In case he doesn't want his name at all on IA Pages either we could display something like "info not available" for the attribution...

**Comment by russellholt** [comment]
I think @MariagraziaAlastra is right about the first part, the user should be given an option to change their attribution - which needs to be subject to review by a human.

But I think all users should have the option to be excluded from attribution, where there should just not be a listing for them. if it's blank I'm not sure what to say but I think 'no info available' sounds like an error.

**Comment by jbarrett** [comment]
Would anyone object if we merged this fix for now and moved the discussion of account handling over to #437?

**Comment by MariagraziaAlastra** [comment]
@jbarrett Sure, go ahead!

**Pull request merged**
