### PR TITLE
IA Pages - edit mode - have separate rows for example query and other queries

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
@russellholt @jagtalon 
screen shot 2015-01-23 at 22 13 23
screen shot 2015-01-23 at 22 13 31

### CODE REVIEW

**Comment by jagtalon** [comment]
@MariagraziaAlastra I'm getting a TypeError on my end--do you see the same thing? `dev` seems to be working well though:

screen shot 2015-01-26 at 11 01 00 am
screen shot 2015-01-26 at 11 01 06 am

**Comment by MariagraziaAlastra** [comment]
@jagtalon Nope, I don't get that error... What did you do exactly? I'm on the same IA Page using the same test account

**Comment by MariagraziaAlastra** [comment]
screen shot 2015-01-26 at 17 05 03

**Comment by jagtalon** [comment]
@MariagraziaAlastra looks like `pre_edit_example_query` isn't here:

```
[11:10 AM ubuntu@jag-bttf templates {maria/example_queries_rows}]$ ls | grep pre_edit
pre_edit_description.handlebars
pre_edit_error.handlebars
pre_edit_issues.handlebars
pre_edit_name.handlebars
pre_edit_other_queries.handlebars
pre_edit_status.handlebars
pre_edit_topic.handlebars
```

**Comment by MariagraziaAlastra** [comment]
@jagtalon Sorry, forgot to add the files to the commit, try again

**Comment by jagtalon** [comment]
@MariagraziaAlastra Nice! I have a few issues but I think they can be worked on other PRs:

- 4 items breaks the layout after editing:
screen shot 2015-01-26 at 11 21 26 am

- I can add the same topic again:
screen shot 2015-01-26 at 11 19 11 am

- Status should probably be a radio button or a dropdown because it's either "live" and "not live" right?
screen shot 2015-01-26 at 11 19 03 am

**Comment by jagtalon** [comment]
@MariagraziaAlastra alright, let's just circle back on the issues above.

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
