### PR TITLE
Dev Page: Initial styling for the dev page

### PR DESCRIPTION
**Pull request by jagtalon**
@MariagraziaAlastra Made some changes to make it look like the mockup that we talked about:

img_0673

I haven't done anything with regards to showing which one is the current milestone--maybe it should be colored green?

So, yeah, still a work in progress but would love some initial feedback (or if I broke something). Screenshots:

screen shot 2015-02-06 at 2 43 53 am
screen shot 2015-02-06 at 2 44 02 am

Arbitrary text works, but kinda gross that it changes the height of just one card.
screen shot 2015-02-06 at 2 47 03 am

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jagtalon Yeah, I think we'll go with green for the current one.

Don't worry about the height of the panels, I'll take care of that in the JS. Since the main PR is still a WIP, too, I'll just merge this in. Thanks!

**Comment by jagtalon** [comment]
@MariagraziaAlastra cool, I'll make a PR for that then

**Comment by MariagraziaAlastra** [comment]
@jagtalon Actually I've already done that

**Comment by jagtalon** [comment]
Nice thanks

**Comment by MariagraziaAlastra** [comment]
@jagtalon Thank *you* for the awesome layout!

**Pull request merged**
