### PR TITLE
commented out add_blogs() when rebuilding test db because it doesn't work

### PR DESCRIPTION
**Pull request by kablamo**
needed to rebuild boxen for john, maria, and russell

### CODE REVIEW

**Comment by kablamo** [comment]
hmm t/blog.t tests seem to fail in travis unless blog data is in the db.

**Comment by jbarrett** [comment]
I think that's unrelated, but I have yet to figure it out. Tests for this branch pass on my dev instance.

**Comment by kablamo** [comment]
I get a different error on your new dev box than travis does:

```
[t::lib::DDGC::TestUtils:6649] error @2015-11-11 13:04:39> Exception caught in 'core.app.before_request' filter: Hook error: DBIx::Class::Storage::DBI::_prepare_sth(): DBI Exception: DBD::SQLite::db prepare_cached failed: no such table: users [for Statement "SELECT me.id, me.username, me.public, me.email_notification_content, me.ghosted, me.ignore, me.email, me.email_verified, me.userpage, me.data, me.notes, me.profile_media_id, me.created, me.updated FROM users me WHERE ( me.username IS NULL )"] at /home/ddgc/community-platform/lib/Dancer2/Plugin/DDGC/Session.pm line 21
 at /home/ddgc/perl5/lib/perl5/Dancer2/Core/App.pm line 953. in /home/ddgc/perl5/lib/perl5/Dancer2/Core/App.pm l. 526
```

**Comment by jbarrett** [comment]
That just looks like there's no schema deployed.

**Comment by kablamo** [comment]
the travis thing must be some difference in version #s compared to the dev box.  anyway.  ok if i merge?

**Pull request merged**
