### PR TITLE
Contributor Profile - fetch issues tags

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
This should fetch tags for all issues and PR, so they'll be available in the frontend for Contributor Profiles.

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Thanks @jbarrett!
screenshot-maria duckduckgo com 5002 2016-05-10 17-03-43

**Comment by jagtalon** [comment]
@MariagraziaAlastra can we make the tags into a JSON array instead of a string?

**Comment by MariagraziaAlastra** [comment]
@jagtalon 
screenshot-maria duckduckgo com 5002 2016-05-10 20-06-21

**Comment by jagtalon** [comment]
@MariagraziaAlastra thank you!

**Comment by MariagraziaAlastra** [comment]
@jbarrett test issue [here](https://github.com/duckduckgo/zeroclickinfo-longtail/issues/59)

**Comment by jagtalon** [comment]
@MariagraziaAlastra I'm getting this when I ran `bin/generate.pl`:

```
[11:05 AM ddgc@jag community-platform {jag/issues-3}]$ bin/generate.pl
Can't use string ("") as an ARRAY ref while "strict refs" in use at /home/ddgc/community-platform/bin/../lib/DDH/UserPage/Gather.pm line 94.
```

Are you getting the same thing?

**Comment by MariagraziaAlastra** [comment]
@jbarrett Is this done? Can I merge?

**Comment by jbarrett** [comment]
:+1: Thanks!

**Comment by jagtalon** [comment]
yeeeeee

**Pull request merged**
