### PR TITLE
Fix ddgc_populate_ia_dev

### PR DESCRIPTION
**Pull request by jbarrett**
Pulling maintainer hash from data before insert.

Still barfs a load of "uninitialized value in concatenation" errors from this [stringification override](https://github.com/duckduckgo/community-platform/blob/9d0f94d5ace1219b87ae784ef00bc603a9859395/lib/DDGC/DB/Base/Result.pm#L278-L281) but I'm not too worried about that for now.

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Seems like it actually updated stuff, although I have an IA Page for a Cheat Sheet for which I changed the repo to "Spice" previously, and althought I do have the correct IA Page for that same Cheat Sheet, the old one with the faulty data wasn't removed. I suppose this is because the meta_id changed:
screenshot-maria duckduckgo com 5001 2016-03-17 19-41-53

Not sure how to avoid duplicates without deleting all the InstantAnswer rows before populating the db again (and I'm not a fan of this strategy). It works well overall, so I'd be happy to merge!

**Comment by jbarrett** [comment]
Thanks @MariagraziaAlastra - since meta_id isn't in the repo JSON I ended up [just using id](https://github.com/duckduckgo/community-platform/blob/bf3ac0f/script/ddgc_populate_ia_dev.pl#L32)

**Comment by MariagraziaAlastra** [comment]
@jbarrett [Actually...](https://github.com/duckduckgo/community-platform/blob/master/lib/DDGC/DB/Result/InstantAnswer.pm#L33)
So the id in the repo JSON is the meta_id. The id is never shown on JSON endpoints.
See also [here](https://github.com/duckduckgo/community-platform/blob/master/lib/DDGC/Web/Controller/InstantAnswer.pm#L112)

**Comment by GuiltyDolphin** [comment]
@jbarrett This for #1257? If so, *sweet!*

**Comment by jbarrett** [comment]
@GuiltyDolphin Don't know how I absolutely missed this report, but yes this should resolve #1257.

You guys did all the leg work, then I did it again!

**Comment by MariagraziaAlastra** [comment]
I think it's good to go. Thanks @jbarrett!

**Comment by GuiltyDolphin** [comment]
@jbarrett Woo! I'll check it out.

**Pull request merged**
