### PR TITLE
Add author to blog feed, add link rel to feed on blog index

### PR DESCRIPTION
**Pull request by jbarrett**

### CODE REVIEW

**Comment by tagawa** [comment]
Looks good except that `<link>` elements should be in the head of an HTML document. Is that possible?
Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Notes

**Comment by tagawa** [comment]
And the `rel` attribute should be `rel="alternate index"`. The `index` value tells the UA that the linked feed is an alternative version of the blog index rather than an individual post.

**Comment by jbarrett** [comment]
Thanks @tagawa!

**Comment by tagawa** [comment]
:+1: @john. Looks good to me!

**Comment by tagawa** [comment]
And the user who reported it says:
"confirmed – awesome – thanks."

**Pull request merged**
