### PR TITLE
Redesign continuation 🐣

### PR DESCRIPTION
**Pull request by jagtalon**
### Things to do:

General 💻:
- [x] Add some padding below to distance the Issues from the footer.
- [x] Increase the distance between the first column and the second column.
- [x] Issues with long names break the layout
- [x] Make the issue icon smaller.
- [x] Align the "created by" with the issue tags
- [x] The text dividers should have an alpha of 0.3
- [x] Add preview - original buttons
- [ ] Example query could be too long

Screenshots 📷:
- [x] Overlay screenshot button
- [x] Make taking screenshots work
- [x] Remove the search bar from the screenshot
- [x] Add buttons for switching between desktop and mobile view.
- [x] Actually make the button switching work
- [x] Add mobile screenshots
- [x] Add a visual cue to show that it's generating the screenshot when there is no screenshot
- [x] Add a visual cue to show that it's generating the screenshot when there is a screenshot
- [x] Add a visual cue to show that it failed generating the screenshot
- [x] Switcher buttons should have a size of 40x40 and the icons themselves 32x32.
- [x] Remove border from the switcher icon when clicked
- [ ] Add a horizontal line between the example and the switcher buttons
- [x] Should not be able to switch when there is an error message or if the screenshot is loading 🔥

Smaller screens 📱:
- [x] Position the second column properly at the bottom
- [x] Make sure everything below the header doesn't break
- [x] Position the buttons properly in the header if they don't fit
- [x] Things break at 320px
- [ ] Resize image when resizing
- [x] .content-wrap should have exactly 2ems of padding--not more.
- [x] 40% opacity for the border in btn--hero
- [x] Add a line to separate the issues and contributors section.
- [x] Hide the label "Categories" on smaller screens

Check / fix breakage 💣:
- [x] Test on other major browsers (tested only on Chrome)
    - [x] Firefox (https://vid.me/AO9s)
    - [x] Safari (https://vid.me/34EI)
    - [x] IE (https://vid.me/InIP)
- [ ] Check functionality of dev page
- [x] Check design of dev page
- [x] Make switching between live and edited page work again
- [x] Check if editing and committing is working
- [x] Make commit link work again
- [x] Check if we're showing the right elements based on the permissions.

Before releasing:
- [ ] We need to regenerate the screenshots
- [ ] Make sure to go through the IA pages to check for edge cases.

### Guides:

issues

ia detail screenshots_0000_layer 5

ia detail screenshots_0001_layer 4

ia detail screenshots_0002_layer 3

ia detail screenshots_0003_layer 2

ia detail screenshots_0004_layer 1

screen shot 2015-06-18 at 3 36 56 pm

screen shot 2015-06-18 at 3 37 39 pm

### CODE REVIEW

**Comment by russellholt** [comment]
looking good so far :+1:

**Comment by jagtalon** [comment]
@MariagraziaAlastra Resizing doesn't break anything anymore https://vid.me/zawf. Most of the design stuff is here and I need your help with these tasks found above:

❑ Make switching between live and edited page work again
❑ Check if editing and committing is working
❑ Make commit link work again
❑ Check if we're showing the right elements based on the permissions.

**Comment by MariagraziaAlastra** [comment]
@jagtalon Done, also a bunch of fixes on the dev page - let me know if I can help you with anything especially JS related

**Comment by jagtalon** [comment]
@MariagraziaAlastra @chrismorast the mobile view should now have a faux mobile device boarder. https://vid.me/X6GF

**Comment by MariagraziaAlastra** [comment]
Ok, merging into my branch. Thanks @jagtalon, great job!

**Pull request merged**
