### PR TITLE
Do not pass ddg links through meta refresh redir

### PR DESCRIPTION
**Pull request by jbarrett**

### CODE REVIEW

**Comment by bsstoner** [comment]
Pretty edge case, but should we worry about cases where `https://duckduckgo.com` might be in the querystring? i.e. `http://something.com?url=http://duckduckgo.com`

**Comment by andrey-p** [comment]
The regex I put together on the spread page could be useful: `^https?:\/\/(\w+\.)?(duckduckgo\.com|duck\.co)`

**Comment by bsstoner** [comment]
Also what about non-https links to `http://duckduckgo.com`? The regex might be a good idea.

You know better than me where this is used and how urgent it is. I'm just trying to spot potential holes. Feel free to merge if you're cool with it :)

**Comment by jbarrett** [comment]
I'm going to go ahead with this, since it fixes an issue we have now and the caveats aren't current issues, going to open a new PR to properly deal with this since I woud like this to be robust.

**Pull request merged**
