### PR TITLE
IA Dev Page - make editing the developer field easier

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
@jagtalon And now make it shine :)

### CODE REVIEW

**Comment by jagtalon** [comment]
@MariagraziaAlastra maybe it shouldn't close when the input is wrong.

https://vid.me/Sg5W

**Comment by MariagraziaAlastra** [comment]
It doesn't close, it's just that it gets refreshed after the attempted saving, and in this case it didn't save anything, so that's why it looks like that :)

**Comment by jagtalon** [comment]
@MariagraziaAlastra what if it didn't try to save when the input is wrong and just changed color?

**Comment by MariagraziaAlastra** [comment]
Yeah let me try that, thanks!

**Comment by jagtalon** [comment]
@MariagraziaAlastra similarly, when the first input is ok, and the second input is bad, they both go away: https://vid.me/Tcqf.

Thanks!

**Comment by MariagraziaAlastra** [comment]
That's weird, I'll look into that, thank you!

**Comment by MariagraziaAlastra** [comment]
@jagtalon Fixed, but when the input is invalid the button is only partially red:
screenshot-maria duckduckgo com 5000 2015-06-05 16-18-06

**Comment by MariagraziaAlastra** [comment]
Alright, thanks @jagtalon! :+1:

**Pull request merged**
