### PR TITLE
Remove IsAwesome IAs from json feed.

### PR DESCRIPTION
**Pull request by zachthompson**
@MariagraziaAlastra @jbarrett  seems silly to have to add this script.  Maybe one of you just wants to execute the sql and close this. ;)

cc @moollaza

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Right, I'll test it in my instance and then run it in staging and prod

**Comment by MariagraziaAlastra** [comment]
Looking good :+1:

**Comment by MariagraziaAlastra** [comment]
All done. Thanks @zachthompson!

**Comment by zachthompson** [comment]
:+1:

**Pull request closed without merging**
