### PR TITLE
Dev Pages - show Fathead-specific section

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
@russellholt data returned from the JSON endpoint after saving:
```json
"src_options":{
    "skip_end":0,
    "skip_abstract":1,
    "skip_qr":0,
    "skip_image_name":0,
    "skip_icon":0,
    "directory":"test",
    "min_abstract_length":"10",
    "skip_abstract_paren":1,
    "is_wikipedia":0,
    "src_info":"",
    "is_mediawiki":0
}
```

Screenshot:
schermata 2015-02-25 alle 19 26 46

### CODE REVIEW

**Comment by russellholt** [comment]
works great, the only thing I'd change now is for `min_abstract_length` to be stored as a number

**Comment by MariagraziaAlastra** [comment]
@russellholt Done :)

**Comment by mrshu** [comment]
@russellholt sorry to interrupt, but `skip_qr` is supposed to be a regular expression and thus I'd expect it to be a string.

Other than that it looks great!

**Comment by MariagraziaAlastra** [comment]
Ah darn, I thought it was a boolean. Thanks @mrshu!

**Comment by mrshu** [comment]
@MariagraziaAlastra no problem at all, I do not see how you would know that =)

**Comment by russellholt** [comment]
thanks @mrshu, did not know that.  grepping gives these examples:

"RuneScape|RuneScapeWiki|RS|Exchange"
"Star Wars Fanon|SWF|SWFanon"

so they're pretty simple

**Comment by russellholt** [comment]
@mrshu do we still use skip_icon? they're all empty

**Comment by mrshu** [comment]
@russellholt yes, they are, one would wonder whether they are regular expressions after all.

While they are rarely used in the DuckDuckHack fatehads (well, they are not used at all) they are strings and they should be represented as such.

Regarding `skip_icon`, that is an old artefact, sources that used them are not enabled at the moment. That being said, I think we could start using them again and so I think we should be ready to support it.

**Comment by MariagraziaAlastra** [comment]
schermata 2015-02-25 alle 23 10 46
schermata 2015-02-25 alle 23 10 48

**Comment by russellholt** [comment]
LGTM

**Comment by mrshu** [comment]
Thanks @MariagraziaAlastra!

**Comment by MariagraziaAlastra** [comment]
Thank you @mrshu @russellholt!

**Comment by russellholt** [comment]
:cactus:

**Pull request merged**
