### PR TITLE
Modal Changes

### PR DESCRIPTION
**Pull request by jagtalon**
- Center the modal
screen shot 2016-01-11 at 1 49 20 pm

### CODE REVIEW

**Comment by jagtalon** [comment]
screen shot 2016-01-11 at 2 09 23 pm

**Comment by jagtalon** [comment]
@MariagraziaAlastra should be good to go

**Comment by MariagraziaAlastra** [comment]
Looks good, thanks @jagtalon :+1:

**Comment by jagtalon** [comment]
@MariagraziaAlastra thanks!

**Pull request merged**
