### PR TITLE
get all comments for a PR including the diff comments

### PR DESCRIPTION
**Pull request by jdorweiler**
We need to use the pull request GH api to get the diff comments on a PR.  The issues api only gives us the regular comments.

### CODE REVIEW

**Comment by jdorweiler** [comment]
wrong branch?  Or maybe master is okay for this?

**Comment by MariagraziaAlastra** [comment]
Master is definitely ok, thanks!

**Comment by MariagraziaAlastra** [comment]
@jdorweiler LGTM :+1:

**Comment by jdorweiler** [comment]
:shipit:

**Pull request merged**
