### PR TITLE
exlusive [sic]

### PR DESCRIPTION
**Pull request by zachthompson**
Update fix typo "goodie_exlusive" (should be exclusive!)  @MariagraziaAlastra can we just run the update statement beginning on [line 28](https://github.com/duckduckgo/community-platform/blob/14b195601adc466d45ad816978b2f452ed5318cf/sql/1.096/dynamic-blocks.sql#L28) to fix these?

hi @jdorweiler

### CODE REVIEW

**Comment by zachthompson** [comment]
Actually we need to update the instant_answer_blockgroup table as well.

**Comment by MariagraziaAlastra** [comment]
@zachthompson Is this still in progress or is it ready to be tested?

**Comment by zachthompson** [comment]
Ready to go!

**Comment by MariagraziaAlastra** [comment]
Thanks @zachthompson, LGTM! :+1:

**Pull request merged**
