### PR TITLE
🍔: Initial version of the hamburger navigation

### PR DESCRIPTION
**Pull request by jagtalon**
screen shot 2016-02-18 at 6 25 40 am

### CODE REVIEW

**Comment by jagtalon** [comment]
screen shot 2016-02-18 at 7 00 11 am

**Comment by jagtalon** [comment]
screen shot 2016-02-18 at 7 20 27 am

**Comment by jagtalon** [comment]
https://v.usetapes.com/uZajKDdZOZ

**Comment by jagtalon** [comment]
@MariagraziaAlastra should be ready for a review

**Comment by chrismorast** [comment]
2 issues;

1. The 'X' is missing 
2. Please create an active state in the menu. @abeyang can mock that up.

**Comment by jagtalon** [comment]
@chrismorast 

Good points! The 'X' should be in there though: https://v.usetapes.com/uZajKDdZOZ

**Comment by jagtalon** [comment]
@chrismorast now it's just the name:

screen shot 2016-02-18 at 11 00 02 am

I think I like this better

**Comment by MariagraziaAlastra** [comment]
@jagtalon Thanks, LGTM! :+1:

**Pull request merged**
