### PR TITLE
Track IA updated timestamp for IA table and its relationships

### PR DESCRIPTION
**Pull request by jbarrett**
- Before any updates:
```
$ curl -I http://localhost:5002/ia/repo/all/json 2>&1 | grep Last
Last-Modified: Thu, 01 Jan 1970 00:00:00 GMT
```

- After updating dev milestone of an IA to deprecated:
```
$ curl -I http://localhost:5002/ia/repo/all/json 2>&1 | grep Last
Last-Modified: Tue, 15 Dec 2015 16:34:25 GMT
```

- After updating the topics of an IA
```
$ curl -I http://localhost:5002/ia/repo/all/json 2>&1 | grep Last
Last-Modified: Tue, 15 Dec 2015 16:35:21 GMT
```

- After updating the description of an IA
```
$ curl -I http://localhost:5002/ia/repo/all/json 2>&1 | grep Last
Last-Modified: Tue, 15 Dec 2015 16:36:26 GMT
```

@jkv Do these cover the failure conditions we discovered?

### CODE REVIEW

**Comment by jbarrett** [comment]
Might it be an idea to add a button to do `schema->resultset('InstantAnswer::LastUpdated')->touch` somewhere?

**Comment by jkv** [comment]
@jbarrett Yes, I believe so.

**Comment by MariagraziaAlastra** [comment]
@jbarrett Looks good to me! Also, tested and it works :+1:

**Comment by jbarrett** [comment]
Thanks @MariagraziaAlastra - merge when ready!

**Pull request merged**
