### PR TITLE
Start using duckduckgo-styles repo

### PR DESCRIPTION
**Pull request by jagtalon**
Move to the new open sourced SCSS files in https://github.com/duckduckgo/duckduckgo-styles.

### CODE REVIEW

**Comment by jagtalon** [comment]
@MariagraziaAlastra should be ready for checking :)

**Comment by jagtalon** [comment]
@MariagraziaAlastra found a bug with the buttons. Fixing it:

screen shot 2015-09-08 at 3 04 36 pm

**Comment by jagtalon** [comment]
@MariagraziaAlastra ok this is ready for realsies.

**Comment by MariagraziaAlastra** [comment]
@jagtalon topics with short names have the x button overlapping the text:
My instance:
screenshot-nimbusscreencaptureff-at-everhelper-dot-me 2015-09-10 17-01-50
Live looks ok:
screenshot-nimbusscreencaptureff-at-everhelper-dot-me 2015-09-10 17-05-11

**Comment by MariagraziaAlastra** [comment]
Same goes for the arrow down in the dropdown (doesn't overlap but it's too close for "Spice" and too far away for "Longtail").
My instance: 
screenshot-nimbusscreencaptureff-at-everhelper-dot-me 2015-09-10 17-08-36
screenshot-nimbusscreencaptureff-at-everhelper-dot-me 2015-09-10 17-10-10

Live:
screenshot-nimbusscreencaptureff-at-everhelper-dot-me 2015-09-10 17-09-38
screenshot-nimbusscreencaptureff-at-everhelper-dot-me 2015-09-10 17-10-31

**Comment by MariagraziaAlastra** [comment]
@jagtalon Too much space before and after the separator, and the color is slightly different (a bit darker) as well.
My instance, detail of an issue on the live page for Airlines:
screenshot-maria duckduckgo com 5001 2015-09-10 17-51-37
Live site:
screenshot-nimbusscreencaptureff-at-everhelper-dot-me 2015-09-10 17-52-01

**Comment by MariagraziaAlastra** [comment]
Everything else looks good!

**Comment by jagtalon** [comment]
@MariagraziaAlastra good finds! Thanks, I'll work on them. :)

**Comment by jagtalon** [comment]
@MariagraziaAlastra ready for another review!

**Comment by MariagraziaAlastra** [comment]
The issues with the dev page are solved, although there's still the separator to fix. 
Thanks! :D

**Comment by MariagraziaAlastra** [comment]
LGTM, thanks @jagtalon! :+1:

**Pull request merged**
