### PR TITLE
IA Pages - bring back the frontend for traffic data

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
Depends on #1087 
//cc @jdorweiler @jagtalon

### CODE REVIEW

**Comment by jagtalon** [comment]
@MariagraziaAlastra the code looks good! I don't see it on my dev instance though--how do I import the data on to my machine?

**Comment by MariagraziaAlastra** [comment]
@jagtalon Yep you need to import the data to see the graphs. There's a [script](https://github.com/duckduckgo/community-platform/blob/b8645d239f92a1d89c974e9b56702e4a1640c802/script/traffic.pl) to run, let me know if that works

**Comment by jagtalon** [comment]
@MariagraziaAlastra thank you! Testing it

**Comment by MariagraziaAlastra** [comment]
Finally merging this stuff :cactus:

**Pull request merged**
