### PR TITLE
Move to using bower when fetching 3rd-party SCSS.

### PR DESCRIPTION
**Pull request by jagtalon**
Run `sudo npm install && bower install && grunt` to test. You need to install bower first `sudo npm install -g bower`.

I can't add `bower` to `package.json` because it's a cli program, unfortunately, and needs to be installed globally.

For @MariagraziaAlastra

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
It seems to compile fine, but I get these warnings:
<pre>bower duckduckgo-colors#* invalid-meta duckduckgo-colors is missing "main" entry in bower.json
bower duckduckgo-colors#* invalid-meta duckduckgo-colors is missing "ignore" entry in bower.json
</pre>

**Comment by jagtalon** [comment]
@MariagraziaAlastra looks like those would have to be added to https://github.com/duckduckgo/duckduckgo-colors/blob/master/bower.json (http://bower.io/docs/creating-packages/#bowerjson). I'll send a PR there.

**Comment by MariagraziaAlastra** [comment]
Cool thanks @jagtalon :)

**Comment by jagtalon** [comment]
@MariagraziaAlastra https://github.com/duckduckgo/duckduckgo-colors/pull/1. This should be good though and no need to wait for that.

**Comment by MariagraziaAlastra** [comment]
:+1:

**Pull request merged**
