### PR TITLE
Populate dev IA data from /ia/repo/all/json

### PR DESCRIPTION
**Pull request by jbarrett**
@MariagraziaAlastra I would appreciate if you tried this out, let me know of any problems.

This does UPSERTs rather than nuking and rebuilding so you should be run it safely as often as required.

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jbarrett So fast!
Anyway it did work without any problem, I'm still looking around to find any issue. 
Since this script uses the ia/repo/all/json endpoint, of course it won't fetch the IAs in planning, deprecated and ghosted dev milestones, but it's probably not important.
We can probably populate the db with IAs in planning by running script/ghIssues.pl anyway

**Comment by jbarrett** [comment]
That last commit will allow you to ignore the milestones filter. It appears to work for me. Of course, it won't work for this script until this goes live.

**Comment by MariagraziaAlastra** [comment]
Cool, thanks @jbarrett!

**Comment by jbarrett** [comment]
@MariagraziaAlastra Hoppy to go ahead with this?

**Comment by MariagraziaAlastra** [comment]
@jbarrett  Sure, works for me! :+1:

**Pull request merged**
