### PR TITLE
Updating social media links in sidebar

### PR DESCRIPTION
**Pull request by tagawa**
##### Description :
Removed RSS feed link (no longer needed) and donttrack.us link.

##### References issues / PRs:
None

##### Who should be informed of this change?
@jbarrett 

##### Does this change have significant privacy, security, performance or deployment implications?
Nope

##### Checklist :
- [ ] Back end tests (perl, scripts)
- [ ] Front end tests (js, integration)
- Browser verification
    - [ ] IE
    - [ ] Chrome
    - [ ] Firefox
    - [ ] Safari
    - [ ] Opera 
- Mobile verification
    - [ ] iOS
    - [ ] Android

### CODE REVIEW

**Comment by tagawa** [comment]
mockup_social-media_duck-co

**Comment by jbarrett** [comment]
@tagawa Could you remove the "Some things you should know" / dontrack.us link while you're in there? The image and site are no longer live.

Thanks!

**Comment by tagawa** [comment]
@jbarrett Good thinking - removed.

**Comment by tagawa** [comment]
@jbarrett I just changed the social media links so they're displayed as a list, staying consistent with the other links in the sidebar. Should be ready for review now - I'll try not to fiddle any more!

mockup_social-media_duck-co2

**Comment by jbarrett** [comment]
👍 Thanks @tagawa! Will try to get this out today.

**Comment by tagawa** [comment]
Gracias monsieur!

**Pull request merged**
