### PR TITLE
IAIndex: Remove the "IsAwesome" IAs.

### PR DESCRIPTION
**Pull request by jagtalon**
There are a lot of IsAwesome IAs, and we might not want to showcase them in the index. Removing them from the list while we figure out what to do with them.

### CODE REVIEW

**Comment by russellholt** [comment]
use the test topic instead

**Comment by jagtalon** [comment]
@russellholt updated!

**Comment by russellholt** [comment]
do you really think grep is the best way to do this? why are we going through the list so many times in so many separate contexts?

**Comment by jagtalon** [comment]
@russellholt made it simpler by adding a `skipTest` helper function that prevents the `li` tag from actually being added. I first started with just hiding the tag, but it ends up being more complicated because clearing the filter could show it again. So best to not put the `<li>` tag in there in the first place.

**Comment by russellholt** [comment]
added WIP label because seems to be not needed, but I want to keep it around until I know we don't need it :8ball:

**Comment by jagtalon** [comment]
@russellholt looks like we don't really need it. Closing.

**Pull request closed without merging**
