### PR TITLE
use HTTP::Tiny

### PR DESCRIPTION
**Pull request by jdorweiler**
Switched ghIssues script to use HTTP::Tiny

@jbarrett @MariagraziaAlastra @russellholt

### CODE REVIEW

**Comment by jbarrett** [comment]
:+1: This is an improvement.

Want to throw this up on wing quickly and see if it works?

**Comment by jdorweiler** [comment]
@jbarrett sure.  How do I do that?

**Comment by jbarrett** [comment]
I just grabbed the raw link:

https://raw.githubusercontent.com/duckduckgo/community-platform/jd/fix_issues/script/ghIssues.pl

...and changed the `use lib` line - appeared to work OK. Can you confirm the data was retrieved as expected?

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Thanks! Tested and it works on my instance. 
Should this solve the issue with the cronjob on the live community platform as well?

**Comment by jdorweiler** [comment]
@MariagraziaAlastra It should.  I tested it out on view.

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Awesome, merging! :+1:

**Pull request merged**
