### PR TITLE
Use bower to pull in the other SCSS dependencies.

### PR DESCRIPTION
**Pull request by jagtalon**
Run `sudo npm install && bower install && grunt` to test. You need to install bower first `sudo npm install -g bower`.

I can't add `bower` to `package.json` because it's a cli program, unfortunately, and needs to be installed globally.

### CODE REVIEW

**Comment by jagtalon** [comment]
For @MariagraziaAlastra 

CC @jdorweiler @jbarrett

**Comment by MariagraziaAlastra** [comment]
@jagtalon Is the import for duckduckgo-colors not going to work anymore, without bower?

**Comment by bsstoner** [comment]
@jagtalon I thought bower got added to chef. Shouldn't that have installed it everywhere for everyone by now?

**Comment by jagtalon** [comment]
@MariagraziaAlastra Yeah--`bower` will pull in the https://github.com/duckduckgo/duckduckgo-colors repo. It's only required for development, and ideally you'd only have to do this once. :)

@bsstoner Yes it should be available to all *.duckduckgo.com dev instances. Since this repo is open source though, other people might be looking at it.

**Comment by MariagraziaAlastra** [comment]
@jagtalon Seems like there's some issue, at least on my instance:
```
 error src/scss/ddgc/main.scss (Line 1: File to import not found or unreadable: ../../../bower_components/duckduckgo-colors/_colors.
Load paths:
  Compass::SpriteImporter
  /home/ubuntu/community-platform/src/scss
  /var/lib/gems/1.8/gems/compass-core-1.0.1/stylesheets)
    error src/scss/ia/main.scss (Line 1: File to import not found or unreadable: ../../../bower_components/duckduckgo-colors/_colors.
Load paths:
  Compass::SpriteImporter
  /home/ubuntu/community-platform/src/scss
  /var/lib/gems/1.8/gems/compass-core-1.0.1/stylesheets)
Compilation failed in 2 files.
Warning: ↑ Use --force to continue.
```

**Comment by jagtalon** [comment]
@MariagraziaAlastra looks like `bower_components` isn't available. Did you try running `bower install` in the root of the repo?

**Comment by gitcxy** [comment]
I am new to duckduckgo/community-platform as well as duckduckgo search engine.  I like the company concept.  a qk suggestion, is it possible to make a color distinguish between title, subtitle and links as the result of a search…check the color difference in google search -- easy to read.

**Comment by jagtalon** [comment]
@gitcxy check out https://duckduckgo.com/settings!

**Comment by jagtalon** [comment]
@MariagraziaAlastra closing this and making a PR to the new dev branch

**Pull request closed without merging**
