### PR TITLE
multiple PRs on IA page

### PR DESCRIPTION
**Pull request by jdorweiler**
Return an array of PRs.  WIP, needs more testing.
selection_074

### CODE REVIEW

**Comment by russellholt** [comment]
this will definitely be an improvement. Do you think we'd need to change the page layout a bit if we wanted to show the PR title?

**Comment by jdorweiler** [comment]
@russellholt yes, I tried adding in the title and it looked cluttered.  I think the status (merged, closed .. ) would be more interesting.

**Comment by MariagraziaAlastra** [comment]
Also we have icons for the status, and the closed/merged PRs could have the strikethrough applied, like in the pipeline

**Comment by jdorweiler** [comment]
Icons would be cool.

**Comment by russellholt** [comment]
try it

**Comment by MariagraziaAlastra** [comment]
screenshot-maria duckduckgo com 5001 2016-01-22 16-23-17

**Comment by jdorweiler** [comment]
Nice!  Do we have an icon for "open"?

**Comment by MariagraziaAlastra** [comment]
Nope

**Comment by jdorweiler** [comment]
Can we get one?  Something like this maybe 
selection_165

**Comment by MariagraziaAlastra** [comment]
The merged and closed icons are custom.
Also I think it's pretty clear that the first one is open

**Comment by jdorweiler** [comment]
Sounds good.

**Comment by MariagraziaAlastra** [comment]
LGTM

**Pull request merged**
