### PR TITLE
Add a custom checkbox

### PR DESCRIPTION
**Pull request by jagtalon**
New:

screen shot 2015-08-20 at 2 19 35 pm

Old:

screen shot 2015-08-20 at 2 14 36 pm

For @chrismorast CC @sdougbrown

### CODE REVIEW

**Comment by jagtalon** [comment]
CC @MariagraziaAlastra

**Comment by russellholt** [comment]
LGTM ...

**Comment by sdougbrown** [comment]
Just got off a call with @jagtalon - he's going to generalize these css selectors a bit more to make this more re-usable.

**Comment by jagtalon** [comment]
@sdougbrown I moved the custom checkbox CSS to _forms.scss like you suggested for clarity.

Other notes:
- No need to change `display: none` to `visibility: hidden`--I tested on different browsers and they all work
- SVGs were updated to be non-responsive so that they work on IE browsers

screen shot 2015-08-26 at 4 17 23 pm

**Comment by sdougbrown** [comment]
That looks good! :+1:

**Comment by jagtalon** [comment]
@sdougbrown thanks!

**Pull request merged**
