### PR TITLE
IA Pages - new IAs are hidden by default if the account isn't verified

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
//cc @russellholt @jdorweiler @jagtalon @jbarrett 
When a user creates a new IA we check for email verification: if the user is verified, the IA will be immediately public, and thus visible on the dev pipeline to non-admins too; 
otherwise it will be hidden until:
- The user is verified, OR
- A PR is linked to the IA Page via ghIssues.pl, OR
- An admin marks it as public by clicking on the button on the page or on the pipeline sidebar.

Screenshots of the button on the single page:
screenshot-maria duckduckgo com 5001 2015-12-24 17-26-22
screenshot-maria duckduckgo com 5001 2015-12-24 17-26-49

On the dev pipeline:
screenshot-maria duckduckgo com 5001 2015-12-24 18-10-37

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Oh, I forgot to mention now the author is immediately added to the contributors, on IA Page creation!

**Comment by MariagraziaAlastra** [comment]
How to test this PR:

#### Test 1: New IAs are always hidden  for regular users if the author doesn't have a verified email
- go to ia/new_ia while logged out;
- try to create a new IA Page;
- sign up (you can either specify a mail right now and not verify it or leave the email field blank);
- after page creation, go to ia/dev/pipeline and see if the IA Page is shown there;
- also check ia/dev/pipeline/json;
- repeat the last two steps while logged out or logged in as another regular (non-admin) user.

Expected result: the new IA Page isn't fetched in the JSON endpoint and thus is not shown in the pipeline.

#### Test 2: hidden New IAs show up in the dev pipeline for admins
- log in using an admin account;
- go to ia/dev/pipeline  and see if the previously created hidden page is shown there.

Expected result: the page is shown, since you're logged in as admin

#### Test 3: email verification makes the user's IA Page public
- log in as the author of the previously created IA Page;
- go to your profile page;
- if you didn't add an email address when you signed up, add one;
- if you did, just click on "verify email";
- go to your email address and click on the verification link;
- go to ia/dev/pipeline and see if the IA Page is now being shown;
- try the same thing while logged out, logged in as a regular user and as an admin.

Expected result: the IA Page is shown in the dev pipeline in all cases.

#### Test 4: admins can toggle the public attribute in the single page
- log in using an admin account;
- go to the IA Page created in Test 1;
- on the right you should see a button "Hide from Dev Pipeline";
- click on it;
- the button should have now changed to "Make public";
- log out;
- go to ia/dev/pipeline and check whether or not the IA Page is shown;
- repeat the last step with any regular non-admin account;
- repeat all from step one (now the button text should be "Make public" before clicking and "Hide from Dev Pipeline" after clicking).

Expected result: after the first iteration the IA Page isn't shown to non-admins on the pipeline - it is shown again after the second iteration of this test.

#### Test 5: admins can toggle the private attribute in the detail sidebar of the dev pipeline
- log in as admin;
- go to ia/dev/pipeline;
- select the IA Page created in Test 1;
- in the sidebar that shows up you should see a "Hide from Dev Pipeline" button;
- click on it;
- close the sidebar;
- log out;
- go back to ia/dev/pipeline and check whether or not the IA Page is shown;
- repeat last step using a regular non-admin account;
- repeat all from step one (the button text will be "Make public" now).

Expected result: after the first iteration the IA Page isn't shown to non-admins on the pipeline - it is shown again after the second iteration of this test.

#### Test 6: IA Pages created by verified users are immediately public
- log in as the author of the IA Page created in Test 1;
- go to ia/new_ia;
- create an IA;
- go to ia/dev/pipeline and check whether it's shown;
- repeat last step while logged out, then while using another regular non-admin account, and then using an admin account;

Expected result: the new IA Page should be visible on the pipeline for everyone.

**Comment by russellholt** [comment]
@moollaza

**Comment by nilnilnil** [comment]
:heart: tests!

**Pull request merged**
