### PR TITLE
Last activity, comments, and commits

### PR DESCRIPTION
**Pull request by jdorweiler**
Added last activity date.
Also added last commit and last comment.  Here's what the data looks like.  Anything else I should get?

```
last_comment = {
    user => users name,
    date => date of comment,
    text => text of comment,
    id => id to link back 
};

last_commit = {
     diff => link to diff,
     user => user name,
     date => date,
     message => commit message,
 };

```

### CODE REVIEW

**Comment by jdorweiler** [comment]
@MariagraziaAlastra

**Comment by MariagraziaAlastra** [comment]
I think that's all we need, thanks @jdorweiler!

**Comment by russellholt** [comment]
LGTM :+1:

**Comment by russellholt** [comment]
If this is good , tested - can we merge ?

**Comment by MariagraziaAlastra** [comment]
It's not tested, I'm having issues with running the script on my instance (but it doesn't depend on this particular change)

**Comment by MariagraziaAlastra** [comment]
Ok tested now, and it works! Thanks @jdorweiler! :+1:

**Pull request merged**
