### PR TITLE
IA Pages - show and edit data source

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
//cc @jagtalon @russellholt 
Dev Page:
screenshot-maria duckduckgo com 5001 2015-12-08 15-37-00
screenshot-maria duckduckgo com 5001 2015-12-08 15-37-21

Live Page:
screenshot-maria duckduckgo com 5001 2015-12-08 15-37-54

Editable Live Page
screenshot-maria duckduckgo com 5001 2015-12-08 15-38-12

Commit Page:
screenshot-maria duckduckgo com 5001 2015-12-08 15-43-51

### CODE REVIEW

**Comment by jagtalon** [comment]
@MariagraziaAlastra lgtm. Take it away, @russellholt

**Comment by russellholt** [comment]
LGTM.

We should extract the 'more at's and stick them in the `src_url` though for the ones that aren't there, otherwise it looks like we don't know what we're talking about since in this case, the more at FlightStats is just a few pixels away from "no data source provided".

From that point of view, it would be best if we could replicate the 'more at' template for the data source - showing the flight stats logo, for instance. ddh2 ..

**Comment by MariagraziaAlastra** [comment]
Sounds good.
Merging, thanks! :+1:

**Comment by jagtalon** [comment]
:+1:

**Pull request merged**
