### PR TITLE
Enable zoom for users with low vision

### PR DESCRIPTION
**Pull request by tagawa**

### CODE REVIEW

**Comment by jbarrett** [comment]
Thanks @tagawa! Due to some bogus decision making on my part, we have two sets of templates which have yet to be merged... Could you make the same change in templates/head.tx?

**Comment by tagawa** [comment]
Sure thing @jbarrett - done!

**Comment by jbarrett** [comment]
Thanks @tagawa!

**Comment by tagawa** [comment]
And :cake: for you @jbarrett.

**Pull request merged**
