### PR TITLE
Userpages - debug info

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
//cc @jagtalon A little addition to your PR :)

### CODE REVIEW

**Comment by bsstoner** [comment]
:+1: looks good. If you want to track anything else on the page (i.e. link clicks), you're probably going to want to move the whole thing to a function. i.e.
```
sendPixel: function(id){
  $('<img src="https://duckduckgo.com/t/' + id + '?' + randomNumber + '" />');
}
```

If you do that you also don't need the `.hide` class.

**Comment by bsstoner** [comment]
@MariagraziaAlastra I was going to merge but it says there's conflicts.

**Comment by MariagraziaAlastra** [comment]
@bsstoner Conflicts fixed. Thanks!

**Comment by bsstoner** [comment]
:+1:

**Comment by MariagraziaAlastra** [comment]
:cactus:

**Pull request merged**
