### PR TITLE
IA Pages - next steps overlay for new contributors

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
WIP! Needs more styling and better wording

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
screenshot-maria-old duckduckgo com 5001 2015-11-26 20-52-44

**Comment by MariagraziaAlastra** [comment]
If the IA has no type:
screenshot-maria-old duckduckgo com 5001 2015-11-26 21-04-27

**Comment by russellholt** [comment]
Is this accessible from a "help" or "next steps" button? (it should be)

The text in this dialog should be specific to this particular IA and this type, not so generic.

- it should have links to the specific relevant sections (spice, etc)
- it should say and link to the specific repo that should be forked
- it should know generally what steps have been done already, eg if there is already a PR, etc.

At the very least, the Create a PR section should say and link to the specific repo that can be forked.

**Comment by russellholt** [comment]
This is a good first draft. we can clean up the language later. @MariagraziaAlastra Merge if you want to test it in staging over the weekend.

**Comment by MariagraziaAlastra** [comment]
@russellholt Thanks!

**Comment by russellholt** [comment]
:+1:

**Pull request merged**
