### PR TITLE
IA Pages - add meta_id column (editable ID)

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
WIP

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@russellholt 
schermata 2015-04-08 alle 21 35 04
schermata 2015-04-08 alle 21 35 11
schermata 2015-04-08 alle 21 35 34

**Comment by russellholt** [comment]
In the edit page, the meta_id is displayed capitalized when it's not stored that way. It should be shown exactly as it is stored. Are other things also displayed that way too?

**Comment by russellholt** [comment]
for /ia/repo  should probably use the meta_id as the key

eg I changed airlines to airlinesx, for
http://russell2.duckduckgo.com:5000/ia/repo/spice/json

screen shot 2015-04-08 at 11 49 59 pm

**Comment by russellholt** [comment]
Looks good besides those two!

**Comment by MariagraziaAlastra** [comment]
@russellholt Yeah everything in the editable page is capitalized. Thanks

**Comment by MariagraziaAlastra** [comment]
@russellholt 
schermata 2015-04-09 alle 12 37 21

**Comment by russellholt** [comment]
LGTM

**Pull request merged**
