### PR TITLE
Userpages - fetch GitHub issues

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
WIP! 
This should get and append issues and pull requests to contributors data, using the GitHub::Issue table as a source.

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Progress:
screenshot-maria duckduckgo com 5002 2016-03-14 20-26-54

**Comment by MariagraziaAlastra** [comment]
@jbarrett Ready for review!
IAs are now stored under a "ia" key, issues under  the "issues" key, and PRs under a "pulls" key.
Full page example screenshot:
screenshot-maria duckduckgo com 5002 2016-03-14 21-32-24

**Comment by MariagraziaAlastra** [comment]
Progress: pair issues and PRs with IAs
screenshot-maria duckduckgo com 5002 2016-03-16 16-13-25

**Comment by jbarrett** [comment]
:+1: Thanks, @MariagraziaAlastra!

**Comment by MariagraziaAlastra** [comment]
:cactus:

**Pull request merged**
