### PR TITLE
IA Dev Page Redesign

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
**Styling:**

Blue Band:
- [x] Missing separators in the static categories line
- [x] The dropdowns are taking up too much space (use JS)
- [x] "Submit" should look disabled when there's nothing to save

Style Detail Section:
- [x] Spice
- [x] Fathead
- [x] Longtail
- [x] Goodie
- [x] Add that wicked border

Triggers:
- [x] Make them look like tabs

Example Queries:
- [x] Make them look like tabs

Description:
- [x] Text area is too small
- [x] Can't seem to expand text area by hand
- [x] Text appears in the middle of the text area

Contributor Popup Styling:
- [x] Center the popup
- [x] Add blue overlay
- [x] Adjust the shadow
- [x] Add check and ! icons
- [x] General styling

Everything else:
- [x] Better checkbox styling 
- [x] Red star near the important fields
- [x] No red star when logged out
- [x] Clicking on "Edit" in the "Dev Machine" scrolls the page back up
- [x] "Commit | Cancel" look swol. Reduce the font-weight.
- [ ] Expand API Documentation and Status Page
- [x] Add padding before the footer
- [x] Remove the edit button space when it's in the dev page
- [x] dropdown looks different in Firefox
- [x] dropdown looks different in windows
- [x] Categories is getting clipped
- [x] Error message below the id
- [ ] Message for the generate screenshot
- [x] Expand tags as we type in
- [x] Screenshot animation
- [x] Checkboxes same size as the input text
- [x] Dev machine dropdown
- [x] Text getting cut off on Firefox

**Testing:**

Browsers / screensizes:
- [ ] Mobile devices
- [x] Major browsers

Permissions:
- [x] No permissions
- [ ] Permissions to edit the IA page
- [x] Admin

Consistency:
- [x] Check consistency between the logged in dev page and logged out
- [x] Check consistency between the static ia page and the logged out view of the dev page 

**Guides:**

ia dev wip 1c - edit in-line

screen shot 2015-07-28 at 11 43 24 am

screen shot 2015-07-28 at 11 51 51 am

screen shot 2015-07-28 at 11 33 08 am

screen shot 2015-07-16 at 4 20 36 pm

ia detail - dev pages detail - fathead

screen shot 2015-07-16 at 4 35 18 pm

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
The static view structure is kinda there:
screenshot-maria duckduckgo com 5001 2015-07-09 19-34-50

Some things for the editable view are there as well, but it needs a lot of work yet, so no screenshot for that :)

**Comment by MariagraziaAlastra** [comment]
Currently:
screenshot-maria duckduckgo com 5001 2015-07-31 17-54-05

With fields open for editing:
screenshot-maria duckduckgo com 5001 2015-07-31 17-57-30

**Comment by MariagraziaAlastra** [comment]
Merging this monster PR, finally :D

**Comment by chrismorast** [comment]
@MariagraziaAlastra , this wasn't ready to merge. In the future please be sure to get sign-off from all parties involved before merging.

**Comment by russellholt** [comment]
Maria and I decided we needed to have it available on view.dukgo.com over the weekend so we can test it. We should have made that clear.

**Pull request merged**
