### PR TITLE
ghIssues.pl - fix adding new developers when developer value is null

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
Checking for a non null / non empty value for the developer was likely preventing new devs from being added unless the field was filled with developers already.

Thanks!

### CODE REVIEW

**Comment by russellholt** [comment]
likely?

**Comment by MariagraziaAlastra** [comment]
Likely as in I don't see any other lines in the code which could do that, beside this.

**Comment by russellholt** [comment]
how do we know this works now? tests and test data?

**Comment by MariagraziaAlastra** [comment]
Remove the developer data for recently merged PRs related to an IA on dev instances, run ghIssues.pl making sure to get the proper time span and see if afterwards the values are filled in.

**Comment by jdorweiler** [comment]
@russellholt there is no easy or automated way.  But in this case I would do the following:
1. delete all the data in the developer column
2. have the script grab a few days worth of issues
3. print a log of each page updated
4. manually check each page

It might be worth generating some test data and figuring out a way to do automated tests.  Or it could be easier just to re-write it be more modular and add unit tests.  What do you think?  I'm interested in working on it if you want.

**Comment by jdorweiler** [comment]
Also, in this case I'll have to manually give it some bad json data to test the `from_json` line that was changed.   Unit tests would be great for this too.

**Comment by russellholt** [comment]
So it seems like the essential untestability of this system is a real flaw. It is not modular; you can't grab github data, run this against that data (offline) and verify that it makes the correct decisions. You can't then regression test against known data. We have no idea unless we literally kill our production data, rerun, and then visually inspect the results?

**Comment by jdorweiler** [comment]
>It is not modular; 

Yes, it's not modular at all

>you can't grab github data, run this against that data (offline) and verify that it makes the correct decisions. 

I'm testing this locally (offline) by grabbing github data using my own personal api token

>You can't then regression test against known data. 

Right

>We have no idea unless we literally kill our production data, rerun, and then visually inspect the results?

Nothing is being killed in production.  I'm testing this locally.

**Comment by MariagraziaAlastra** [comment]
//cc @jbarrett I added that script to update the contributors based on historical data, do you want to have a look as well?

**Comment by jdorweiler** [comment]
The only cases I've found where we're missing a developer are a few internal fatheads and one IA page that looks like it should be removed anyway (https://duck.co/ia/view/coffeetowaterratio).  I fixed all the fatheads already. 

```
jd@JD:~$ wget -O repo_all.json http://duck.co/ia/repo/all/json
--2016-04-14 17:55:25--  http://duck.co/ia/repo/all/json
Resolving duck.co (duck.co)... 54.208.102.63
Connecting to duck.co (duck.co)|54.208.102.63|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://duck.co/ia/repo/all/json [following]
--2016-04-14 17:55:25--  https://duck.co/ia/repo/all/json
Connecting to duck.co (duck.co)|54.208.102.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 784971 (767K) [application/json]
Saving to: ‘repo_all.json’

100%[=================================================================================================================================================================================================================================>] 784,971     1.83MB/s   in 0.4s   

2016-04-14 17:55:28 (1.83 MB/s) - ‘repo_all.json’ saved [784971/784971]

jd@JD:~$ jq '.[] | if .developer == null then .id else "none" end' repo_all.json | sed -n '/none/!p'
"wikipedia_norwegian"
"doraemon"
"zeldawiki"
"wikipedia_norwegian_nynorsk"
"coffeetowaterratio"
"wikipedia_japanese"
"sports"
"mlp_wiki"
"callofduty"
"futurama"
```

I ran screen shots on 200 pages that were updated when testing and didn't see anything weird.

**Pull request merged**
