### PR TITLE
Dev Page Redesign - tweaks on the contributors popup

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
@jagtalon the close icon needs styling though:
screenshot-maria duckduckgo com 5001 2015-08-10 16-03-40

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
Woops, lloks like Jag is out today! @russellholt @chrismorast 
screenshot-maria duckduckgo com 5001 2015-08-10 16-46-02

**Comment by jagtalon** [comment]
@MariagraziaAlastra 

Now using the ddgsi-warning symbol

screen shot 2015-08-10 at 11 52 17 am

**Comment by jagtalon** [comment]
screen shot 2015-08-10 at 12 02 08 pm
screen shot 2015-08-10 at 12 02 17 pm
screen shot 2015-08-10 at 12 02 28 pm

**Comment by MariagraziaAlastra** [comment]
committing contributors works again, merging

**Comment by russellholt** [comment]
:+1: aww yeah

**Pull request merged**
