### PR TITLE
Userpages - gather avatars for all IAs contributors

### PR DESCRIPTION
**Pull request by MariagraziaAlastra**
//cc @jagtalon 
screenshot-maria duckduckgo com 5002 2016-04-01 20-38-29

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jbarrett yeah, that was it! I'll make it case insensitive as well, thanks :)

**Comment by MariagraziaAlastra** [comment]
@jbarrett Done!

**Comment by jbarrett** [comment]
:+1: Thanks @MariagraziaAlastra!

**Comment by MariagraziaAlastra** [comment]
:cactus:

**Pull request merged**
