### PR TITLE
add file paths when a pr is merged

### PR DESCRIPTION
**Pull request by jdorweiler**
This is kinda hard to test since a PR needs to be merged to test it.  I tested it out my flipping some of the data from the github api to make it look like a pr was merged and it worked fine.

I'll explain the idea since it's difficult to test.
1. First go to our db and get all of the issues marked at being a pr
2. build a hash of pull requests.  pull_request_number+repo => { pull request data }
3. Get the current issues for the repo
4. When we get a new issue from the API we delete it from the pr hash.  The idea being that anything that is still live hasn't been merged/closed
5. If there's anything left in the pr hash at the end of checking the current issues then it has either been merged or closed.  Run the merge_files sub

merge_files sub
1. get detailed data on the issue
2. check if it has a merged_at data
3. get the detailed file info for the pr
4. update code column in our db.

@russellholt @MariagraziaAlastra

### CODE REVIEW

**Comment by MariagraziaAlastra** [comment]
@jdorweiler Thanks for this! So, how would you like to proceed? The code looks good and I don't get any errors, so I guess it's fine (unless we want to wait for some PR to be merged)

**Comment by jdorweiler** [comment]
I think it's okay to merge.  I did some testing and it worked fine.  The update is done in a transaction so nothing too bad can happen :)

**Comment by MariagraziaAlastra** [comment]
Roger :cactus:

**Comment by russellholt** [comment]
:+1:

**Pull request merged**
